version: '3.8'

services:
  ikuai-komari-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ikuai-komari-agent
    restart: unless-stopped
    
    # 环境变量配置 - 从.env文件读取
    env_file:
      - .env
    
    # 或者直接在这里设置环境变量（可选）
    environment:
      # iKuai路由器配置
      - IKUAI_BASE_URL=${IKUAI_BASE_URL:-http://192.168.1.1}
      - IKUAI_USERNAME=${IKUAI_USERNAME:-admin}
      - IKUAI_PASSWORD=${IKUAI_PASSWORD:-admin}
      - IKUAI_TIMEOUT=${IKUAI_TIMEOUT:-10}
      
      # Komari服务器配置
      - KOMARI_ENDPOINT=${KOMARI_ENDPOINT:-https://komari.server.com}
      - KOMARI_TOKEN=${KOMARI_TOKEN:-your_token_here}
      - KOMARI_WEBSOCKET_INTERVAL=${KOMARI_WEBSOCKET_INTERVAL:-1.0}
      - KOMARI_BASIC_INFO_INTERVAL=${KOMARI_BASIC_INFO_INTERVAL:-5}
      - KOMARI_IGNORE_UNSAFE_CERT=${KOMARI_IGNORE_UNSAFE_CERT:-False}
      
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/ikuai_agent.log
      - LOG_MAX_BYTES=${LOG_MAX_BYTES:-10485760}
      - LOG_BACKUP_COUNT=${LOG_BACKUP_COUNT:-3}
    
    # 卷挂载 - 持久化日志
    volumes:
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro  # 同步主机时间
    
    # 网络模式 - 使用主机网络以便访问局域网设备
    network_mode: host
    
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f ikuai_komari_agent.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
